---
title: "TS Covid Analysis EDA"
author: "Lijju Mathew"
date: "11/21/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r imports}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(GGally)
library(astsa)
library(tswge)
library(lubridate)
set.seed(1234)
options(scipen=10000)
```

```{r function to calcualte rolling window}

rolling_ase <-  function (data, phis,thetas, d, s, training_size, horizon,total) {
  
phis1 = phis
thetas1 = thetas
s1  = s
d1  = d

trainingSize = training_size
horizon = horizon
ASEHolder1 = numeric()

for( i in 1:(total-(trainingSize + horizon) + 1)) {
  forecasts1 = fore.aruma.wge(data[i:(i+(trainingSize-1))],phi = phis1, theta = thetas1, s = s1, d = d1,n.ahead = horizon)
  ASE = mean((data[(trainingSize+i):(trainingSize+ i + (horizon) - 1)] - forecasts1$f)^2)
  ASEHolder1[i] = ASE
}

ASEHolder1
hist(ASEHolder1, main = paste("Histogram of Model ASEs" ))
WindowedASE1 = mean(ASEHolder1)

summary(ASEHolder1)
WindowedASE1
}
```

```{r IL read and plot data}
il_covid_dataset = "https://raw.githubusercontent.com/lijjumathew/MSDS-Time-Series-Covid-Analysis/master/Data/illinois-history.csv"
il_covid_rawdata <- read.csv(il_covid_dataset, sep = ",", header = TRUE)
head(il_covid_rawdata)
il_covid_data <- il_covid_rawdata %>% map_df(rev)
il_covid_data$dailyPositivityRate = (il_covid_data$positiveIncrease/il_covid_data$totalTestResultsIncrease)*100
head(il_covid_data)
summary(il_covid_data$dailyPositivityRate)
plot(il_covid_data$dailyPositivityRate)
il_covid_ts <- ts(il_covid_data$dailyPositivityRate, start =decimal_date(as.Date("2020-03-15")), frequency = 365)
summary(il_covid_ts)
plotts.sample.wge(il_covid_ts)
length(il_covid_ts)

df_il <- il_covid_data
df_il$date_mod=as.POSIXct(df_il$date, format="%m/%d/%y")
attach(df_il)
df_il_vis <- df_il %>% select(date_mod, death, negative,positive,totalTestResults) %>%   gather(key = "variable", value = "value",-date_mod)

ggplot(df_il_vis, aes(x = date_mod, y = value)) +   
  geom_line(aes(color = variable, linetype = variable)) + 
  ggtitle("Covid Counts - IL State") +
  xlab("Dates") + ylab("Counts")
```

```{r IL Identifying the order and (p,q,d,s)}
il_covid_diff1=artrans.wge(il_covid_ts,phi.tr=1)
plotts.wge(il_covid_diff1)
plotts.sample.wge(il_covid_diff1)
aic5.wge(il_covid_diff1,type = "aic")
aic5.wge(il_covid_diff1,type = "bic") 
# Both AIC and BIC produces p=4, q=2 as best model.
# BIC produces p=2 and q=1 as second best model.
aic5.wge(il_covid_diff1, p=0:10, q=0:10, type = "aic")
# Produces p=8, q=5 as best model.
aic5.wge(il_covid_diff1, p=0:10, q=0:10, type = "bic")
# Produces p=4, q=2 as best model.
```

```{r IL Model identification}
#Model ARIMA(4,1,2)
il_m1=est.arma.wge(il_covid_diff1,p=4,q=2)
il_m1$phi
il_m1$theta
il_model1=fore.aruma.wge(il_covid_ts, phi=il_m1$phi,theta=il_m1$theta,d=1,n.ahead=30,lastn = TRUE)
ase_il_model1 = mean((il_covid_ts[222:251] - il_model1$f)^2)
ase_il_model1
rolling_ase(il_covid_ts,il_m1$phi,il_m1$theta,1,0,100,30,251)
#Model ARIMA(2,1,1)
il_m2=est.arma.wge(il_covid_diff1,p=2,q=1)
il_model2=fore.aruma.wge(il_covid_ts, phi=il_m2$phi,theta=il_m2$theta,d=1,n.ahead=30,lastn = TRUE)
ase_il_model2 = mean((il_covid_ts[222:251] - il_model2$f)^2)
ase_il_model2
rolling_ase(il_covid_ts,il_m2$phi,il_m2$theta,1,0,100,30,251)


il_model1=fore.aruma.wge(il_covid_ts, phi=il_m1$phi,theta=il_m1$theta,d=1,n.ahead=30,lastn = FALSE)
il_model1=fore.aruma.wge(il_covid_ts, phi=il_m1$phi,theta=il_m1$theta,d=1,n.ahead=90,lastn = FALSE)
```


```{r National read and plot data}
us_covid_dataset = "https://raw.githubusercontent.com/lijjumathew/MSDS-Time-Series-Covid-Analysis/master/Data/national-history.csv"
us_covid_rawdata <- read.csv(us_covid_dataset, sep = ",", header = TRUE)
head(us_covid_rawdata)
# Reverse the order of data i.e from March to November
us_covid_data <- us_covid_rawdata %>% map_df(rev)
us_covid_data$dailyPositivityRate = (us_covid_data$positiveIncrease/us_covid_data$totalTestResultsIncrease)*100
head(us_covid_data)
summary(us_covid_data$dailyPositivityRate)
plot(us_covid_data$dailyPositivityRate)
us_covid_ts <- ts(us_covid_data$dailyPositivityRate, start =decimal_date(as.Date("2020-03-15")), frequency = 365)
summary(us_covid_ts)
plotts.sample.wge(us_covid_ts)
length(us_covid_ts)


df_us <- us_covid_data
df_us$date_mod=as.POSIXct(df_us$date, format="%m/%d/%y")
attach(df_us)
df_us_vis <- df_us %>% select(date_mod, death, negative,positive,totalTestResults) %>%   gather(key = "variable", value = "value",-date_mod)

ggplot(df_us_vis, aes(x = date_mod, y = value)) +   
  geom_line(aes(color = variable, linetype = variable)) + 
  ggtitle("Covid Counts - USA") +
  xlab("Dates") + ylab("Counts")
```


```{r National Identifying the order and (p,q,d,s)}
us_covid_diff1=artrans.wge(us_covid_ts,phi.tr=1)
plotts.wge(us_covid_diff1)
plotts.sample.wge(us_covid_diff1)
aic5.wge(us_covid_diff1,type = "aic")
aic5.wge(us_covid_diff1,type = "bic") 
# AIC produces p=5, q=1 as best model, BIC as p=0, q=1
aic5.wge(us_covid_diff1, p=0:15, q=0:10, type = "aic")
# Produces p=14, q=2 as best model.
aic5.wge(us_covid_diff1, p=0:10, q=0:10, type = "bic")
# Produces p=5, q=1 as best model.

```

```{r National Model identification}
#Model ARIMA(5,1,1)
us_m1=est.arma.wge(us_covid_diff1,p=5,q=1)
us_m1$phi
us_m1$theta
us_model1=fore.aruma.wge(us_covid_ts, phi=us_m1$phi,theta=us_m1$theta,d=1,n.ahead=30,lastn = TRUE)
ase_us_model1 = mean((us_covid_ts[222:251] - us_model1$f)^2)
ase_us_model1
rolling_ase(us_covid_ts,us_m1$phi,us_m1$theta,1,0,100,30,251)

#Model ARIMA(0,1,1)
us_m2=est.arma.wge(us_covid_diff1,p=0,q=1)
us_model2=fore.aruma.wge(us_covid_ts, phi=us_m2$phi,theta=us_m2$theta,d=1,n.ahead=30,lastn = TRUE)
ase_us_model2 = mean((us_covid_ts[222:251] - us_model2$f)^2)
ase_us_model2
rolling_ase(us_covid_ts,us_m2$phi,us_m2$theta,1,0,100,30,251)

us_model1=fore.aruma.wge(us_covid_ts, phi=us_m1$phi,theta=us_m1$theta,d=1,n.ahead=30,lastn = FALSE)
us_model1=fore.aruma.wge(us_covid_ts, phi=us_m1$phi,theta=us_m1$theta,d=1,n.ahead=90,lastn = FALSE)
```

